config/routes.rb
Medicaldevicehub::Application.routes.draw do

  resources :videourls

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :manufacturers

  root :to => 'pages#index'

  get 'about' => 'pages#about'
  get 'mdr' => 'pages#mdr'
  get 'mma' => 'pages#mma'
  get 'privacy' => 'pages#privacy'
  get 'tos' => 'pages#tos'
  get 'udi' => 'pages#udi'
  get 'contacts' => 'contacts#new'

  resources :medicaldevices, except: [:destroy, :edit, :update]

  resources :device_reviews

  resources :manufacturers

  resources :contacts, only: [:new, :create]

  resources :medicaldevices do
    resources :videourls
  end
  resources :manufacturers do
    resources :videourls
  end

end

app/models/medicaldevice.rb
class Medicaldevice < ActiveRecord::Base

	validates :trade_name, :uniqueness => true
	validates :applicant, :presence => true
	validates_presence_of :trade_name, :unless => :generic_name?

	belongs_to :manufacturer
	has_many :device_reviews, :dependent => :destroy
  has_many :videourls, :dependent => :destroy

	mount_uploader :image, ImageUploader

  scope :similar_devices, -> (medicaldevice) {where("id != ? and product_code= ?", medicaldevice.id, medicaldevice.product_code)}



    # Search:-

        	include PgSearch
        	pg_search_scope :search, :against => [ :generic_name, :trade_name, :description, :applicant],
        	using: [tsearch: {dictionary: "english"}],
        	ignoring: :accents

        	def self.text_search(query)
        		if query.present?
        			rank = <<-RANK
              			ts_rank(to_tsvector(generic_name), plainto_tsquery(#{sanitize(query)})) +
              			ts_rank(to_tsvector(trade_name), plainto_tsquery(#{sanitize(query)}))+
              			ts_rank(to_tsvector(description), plainto_tsquery(#{sanitize(query)})) +
              			ts_rank(to_tsvector(applicant), plainto_tsquery(#{sanitize(query)}))
            		RANK


            	where("to_tsvector('english', generic_name) @@ plainto_tsquery(:q) or to_tsvector('english', trade_name) @@ plainto_tsquery(:q) or to_tsvector('english', description) @@ plainto_tsquery(:q) or to_tsvector('english', applicant)@@ plainto_tsquery(:q)", q: query).order("#{rank} DESC")

        		else
        			all
        		end
        	end

       def to_param
          if trade_name.present?
            "#{id}-#{trade_name.parameterize}"
          else
            "#{id}-#{generic_name.parameterize}"
          end
       end






      #	after_save :enqueue_image

        def image_name
          File.basename(image.path || image.filename) if image
        end

       # def enqueue_image
       #   ImageWorker.perform_async(id, key) if key.present?
       # end

        class ImageWorker
          include Sidekiq::Worker

          def perform(id, key)
            medicaldevice = Medicaldevice.find(id)
            medicaldevice.key = key
            medicaldevice.remote_image_url = medicaldevice.image.direct_fog_url(with_path: true)
            medicaldevice.save!
            medicaldevice.update_column(:image_processed, true)
          end
        end

end

app/controllers/medicaldevices_controller.rb
class MedicaldevicesController < ApplicationController
  before_action :set_medicaldevice, only: [:show, :edit, :update]
  before_action :authenticate_manufacturer!, except: [:index, :show]

  # GET /medicaldevices
  # GET /medicaldevices.json
  def index
    @medicaldevices = Medicaldevice.limit(40)
    @medicaldevices = Medicaldevice.text_search(params[:query]).page(params[:page])
    @uploader = Medicaldevice.new.image
    @uploader.success_action_redirect = @medicaldevice
  end

  # GET /medicaldevices/1
  # GET /medicaldevices/1.json
  def show
    @medicaldevice = Medicaldevice.find(params[:id])
    @device_review= DeviceReview.new(:medicaldevice => @medicaldevice)
    @device_review.user= current_user
    current_medicaldevice = @medicaldevice
    @videourls = @medicaldevice.videourls
    device_reviews= @medicaldevice.device_reviews
    @similar_devices= Medicaldevice.similar_devices(@medicaldevice).limit(10)
  end

  # GET /medicaldevices/new
  def new
    @medicaldevice = Medicaldevice.new
    @medicaldevices = Medicaldevice.new(key: params[:key])
    @videourl = @medicaldeivce.Videourl.new(videourl_params)
  end

  # GET /medicaldevices/1/edit
  def edit
    @medicaldevice = Medicaldevice.find(params[:id])
    @videourl = @medicaldeivce.Videourl.new(videourl_params)
  end

  # POST /medicaldevices
  # POST /medicaldevices.json
  def create
    @medicaldevice = Medicaldevice.new(medicaldevice_params)

    respond_to do |format|
      if @medicaldevice.save
        format.html { redirect_to @medicaldevice, notice: 'Medicaldevice was successfully created.' }
        format.json { render action: 'show', status: :created, location: @medicaldevice }
      else
        format.html { render action: 'new' }
        format.json { render json: @medicaldevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /medicaldevices/1
  # PATCH/PUT /medicaldevices/1.json
  def update
    respond_to do |format|
      if @medicaldevice.update(medicaldevice_params)
        format.html { redirect_to @medicaldevice, notice: 'Medicaldevice was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @medicaldevice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /medicaldevices/1
  # DELETE /medicaldevices/1.json
  def destroy
    @medicaldevice.destroy
    respond_to do |format|
      format.html { redirect_to medicaldevices_url }
      format.json { head :no_content }
    end
  end

 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_medicaldevice
      @medicaldevice = Medicaldevice.find(params[:id])
    end

    def correct_manufacturer
      @medicaldevice = correct_manufacturer.medicaldevices.find_by(id: params[:id])
      redirect_to medicaldevices_path, notice: "Not authorized to edit this medicaldevice" if @medicaldevice.nil?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def medicaldevice_params
      params.require(:medicaldevice).permit(:pmak_number, :applicant, :street1, :street2, :city, :state, :zip, :generic_name, :trade_name, :product_code, 
        :advisory_committee, :description, :image, :remove_image, :manufacturer_id, :slug)
    end

    def set_videourl
      @videourl = Videourl.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def videourl_params
      params.require(:videourl).permit(:description, :body_html, :medicaldevice_id, :manufacturer_id, :title, :body)
    end
end

app/helpers/medicaldevices_helper.rb
module MedicaldevicesHelper
end

app/views/medicaldevices/_form.html.erb
<%= simple_form_for(@medicaldevice) do |f| %>
  <% if @medicaldevice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@medicaldevice.errors.count, "error") %> prohibited this medicaldevice from being saved:</h2>

      <ul>
      <% @medicaldevice.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pmak_number %><br>
    <%= f.text_area :pmak_number %>
  </div>

  <div class="field">
    <%= f.label :applicant %><br>
    <%= f.text_area :applicant %>
  </div>
  <div class="field">
    <%= f.label :street1 %><br>
    <%= f.text_area :street1 %>
  </div>
  <div class="field">
    <%= f.label :street2 %><br>
    <%= f.text_area :street2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_area :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_area :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_area :zip %>
  </div>
  <div class="field">
    <%= f.label :generic_name %><br>
    <%= f.text_area :generic_name %>
  </div>
  <div class="field">
    <%= f.label :trade_name %><br>
    <%= f.text_area :trade_name %>
  </div>
  <div class="field">
    <%= f.label :product_code %><br>
    <%= f.text_area :product_code %>
  </div>
  <div class="field">
    <%= f.label :advisory_committee %><br>
    <%= f.text_area :advisory_committee %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>


   <div class = "field">
    <%= image_tag(@medicaldevice.image_url) if @medicaldevice.image? %>
 
    <%= f.label :image %>
    <%= f.file_field :image %>
  <p>
    <label>

      <%= f.check_box :remove_image %>
      <%= f.label :remove_image, "Remove image" %>
    </label>
  </div>

  <div class="form-actions">
    <%= f.submit "Add or Update a Device", class: "btn btn-primary" %>
  </div>
 
<% end %>

app/views/medicaldevices/edit.html.erb
<h1>Editing medicaldevice</h1>

<%= render 'form' %>

 <%= render partial: 'videourls/form' %>

<%= link_to 'Show', @medicaldevice %> |
<%= link_to 'Back', medicaldevices_path %>

app/views/medicaldevices/index.html.erb
<%= render 'layouts/search' %>

<%= link_to 'Add a new Medical Device', new_medicaldevice_path, :class => 'btn btn-primary'  if manufacturer_signed_in? %>

<div id="device-box">     
      <% if @medicaldevices.present? %>

      <h1>Listing medicaldevices</h1>

              <table>
                <thead>
                  <tr>
                    <th>Device Image </th>
                    <th>Generic Name</th> 
                    <th>Trade name</th>
                    <th>Manufacturer</th>
                  </tr>
                </thead>

                <tbody>
                    <% @medicaldevices.each do |medicaldevice| %>
                    
                          <tr height = "60px" class= "<%= cycle('list_line_odd', 'list_line_even') %>">
                            <td>
                              <%= link_to image_tag(medicaldevice.image_url, class: 'deviceimage-thumbnail'),medicaldevice_path(medicaldevice)%>
                            </td>
                            <td>
                              <%= link_to medicaldevice.generic_name, medicaldevice_path(medicaldevice) %>
                            </td>
                            <td>
                              <% if medicaldevice.generic_name.present? %>
                              <%= medicaldevice.trade_name %>
                              <%else %>
                               <%= link_to medicaldevice.trade_name, medicaldevice_path(medicaldevice)%>
                               <%end %>
                            </td>

                            <td>
                              <%= medicaldevice.applicant %>
                            </td>
                          </tr>
                        <% end %>
                </tbody>

              </table>
      <% else %>
      <div>Sorry! No Devices Found. Please Contact Us for More info.</div>
      <% end %>

      <br>

      <%= link_to 'Back to Home Page', root_path, :class => 'btn btn-primary' %>
</div>

app/views/medicaldevices/new.html.erb
<h2>Add a new Medical Device</h2>

<%= render 'form' %>

<%= link_to 'Back', medicaldevices_path %>

app/views/medicaldevices/show.html.erb
<div class= "search-box">
  <%= render 'layouts/search' %>
</div>


<p id="notice"><%= notice %></p>

  <div class ="container">
    <div class="row">
                          <div class= "col-md-4 col-sx-5">
                            <h3><strong>Device Image:</strong></h3> 
                              <div class="device-image">
                                <% if @medicaldevice.image? %>
                                    <%= image_tag @medicaldevice.image.url.to_s %>
                                    <% else %>
                                    <%= image_tag("default-image2.jpg", :alt => "default image") %>
                                    <% end %> 
                              </div>
                          </div>
                        

                    <div class= "col-md-8 col-sx-7">
                      <h3><strong>Device Information:</strong></h3> 
                        <p class="device-number">
                          <strong>PMN or PMA number:</strong>
                          <%= @medicaldevice.pmak_number %>
                        </p>      

                          
                        <h5 class="device-heading"><strong>Trade Name:</strong></h5> 
                        <p><h4><%= @medicaldevice.trade_name %></h4></p>
                                              
                        <h5 class="device-heading"><strong>Generic Name:</strong></h5>
                        <p><h4> <%= @medicaldevice.generic_name %> </h4></p>
                        
                    
                        <h5 class="device-heading"><strong>Manufacturer/Applicant:</strong></h5>
                        <p><h4><%= @medicaldevice.applicant %></h4></p>

                        <h5 class="device-heading"><strong>Description:</strong></h5>
                        <p><%= truncate(@medicaldevice.description, length: 240, separator: ' ') %></p>
                    </div>
      </div>


      <div class="row">
              <div class="col-md-7 col-sx-7 device-video">
                <p>
                    <Strong><h3> Watch How-To Video: </h3></Strong>
                    
                     <div class="">
                       
                       <% if @medicaldevice.videourls.any? %>
                                    
                              <%= render @medicaldevice.videourls.last %>
                       
                          <% else %>
                               <div class="default-video-image">
                                      <%= image_tag("default-video.png", :alt => "default video image") %>
                               </div>
                          <% end %> 
                          
                    </div>
                </p>
              </div>

              <div class="col-md-5 col-sx-5">
                <p>
                    <Strong><h4> View Similar Medical Devices: </h4></Strong>
                </p>
                <div>
                  <table>
                            <thead>
                              <tr>
                                <th>Image </th>
                                <th>Generic Name</th> 
                                <th>Trade Name</th>
                              </tr>
                            </thead>

                            <tbody>
                                <% @similar_devices.each do |medicaldevice| %>
                                
                                      <tr height = "50px" class= "<%= cycle('list_similar_line_odd', 'list_similar_line_even') %>">
                                        <td width= "80px">
                                          <%= image_tag(medicaldevice.image_url, class: 'deviceimage-thumbnail')%>
                                        </td>
                                        
                                        <td>
                                          <%= link_to medicaldevice.generic_name, medicaldevice_path(medicaldevice) %>
                                        </td>
                                        <td>
                                          <% if medicaldevice.generic_name.present? %>
                                          <%= medicaldevice.trade_name %>
                                          <%else %>
                                           <%= link_to medicaldevice.trade_name, medicaldevice_path(medicaldevice)%>
                                           <%end %>
                                        </td>
                                      </tr>
                                    <% end %>
                            </tbody>
                  </table>
                </div>
              </div>
      </div>



        <div class="row device-page-contact-button">

            <h4> LOOKING FOR SPECIFIC INFORMATION ON ANY MEDICALDEVICE? <%= link_to "Contact Us", new_contact_path, :class =>"btn btn-danger btn-lg" %></h4>
        </div>
              
              <div class="row">
                <div class="col-md-8 col-sx-7">

                  <p>
                    <Strong><h3> Device Reviews: </h3></Strong>
                  </p>
                  <ol>
                   <% @medicaldevice.device_reviews.each do |review| %>
                      <li>
                         <p>By: <%= review.user.username %> </p>
                         <p> <%= review.content %> </p> 
                        <% end %>
                      </li>
                  </ol>

                    <%= render partial: 'device_reviews/form' %>
                  </div>

              </div>
    <div class= "back-to-home">
        <%= link_to 'Back to Home', root_path, :class => "btn btn-success"  %>
    </div>

  </div> <!-- end container>