config/routes.rb
Medicaldevicehub::Application.routes.draw do

  resources :videourls

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :manufacturers

  root :to => 'pages#index'

  get 'about' => 'pages#about'
  get 'mdr' => 'pages#mdr'
  get 'mma' => 'pages#mma'
  get 'privacy' => 'pages#privacy'
  get 'tos' => 'pages#tos'
  get 'udi' => 'pages#udi'
  get 'contacts' => 'contacts#new'

  resources :medicaldevices, except: [:destroy, :edit, :update]

  resources :device_reviews

  resources :manufacturers

  resources :contacts, only: [:new, :create]

  resources :medicaldevices do
    resources :videourls
  end
  resources :manufacturers do
    resources :videourls
  end

end

app/views/pages/about.html.erb
<% content_for :title do %>About Medical Device Hub<% end %>
<div class="row">
	<div class="container">
		<h2>About Medical Device Hub</h2>
		<p>Medical Device Hub is a web portal that aggregates information on Medical Devices available worldwide. MedicalDeviceHub's mission, and the focus around the world, is to improve the quality of health care by collecting high quality information on innovative, high-quality medical device products from medical device manufacturers and providing it to users and patients. Our emphasis is on our users' satisfaction.Our organization's mission is to demonstrate world class service, and be a responsible entity for providing value to the local as well as global communities.</p>

		<h3>For Users:</h3>

			<ol>
				<p>
					<li>
						MedicalDeviceHub  lists 140,000 medical devices from more than 24,000 manufacturers worldwide and attracts several thousands regular visitors across Globe.
					</li>
				</p>
				<p>
					 <li>
					MedicalDeviceHub Inc.  brings your device to global audience and customers using several social media strategies (Youtube, Facebook, twitter and Pinterest and several other social media platforms).
					 </li>
				</p>

				<p>
					   <li>
					We create awesome professional videos on what is the device, how it works and how to use at different settings (At hospital or home). The videos can be of several categories such as for healthcare professionals or towards consumers.
					  </li>
				</p>

				<p>

				   	<li>
						We also create and in-depth text description of Medical device with specifications relevant to customers.
				 	</li>
			 	</p>
			</ol>

		<h3> For Manufacturers: </h3>	
		<ol>
			<p>
				<li>
					MedicalDeviceHub Inc. helps increase the revenues by bringing more exposure of Medical Device companies products by marketing to consumer. Each month we reach 2 million consumers on the web through different social media sites such as Youtube, Twitter and Facebook with an audio message.
				</li>
			</p>
			<p>
				<li>
					We have automated the device warning and alert system, where we notifies the manufactures if there are some warning or alert pops up on the web.
					So that the device manufacturers can be alerted on ongoing device related issues
		  		</li>
			</p>
			<p>	
			   <li>
					We also alert you if there is a new similar/ competitive device enters into the market.
			   </li>
			</p>

		</ol>
	</div>
</div>

app/views/pages/home.html.erb
<%= render 'layouts/search' %>

<h1>Listing medicaldevices</h1>

<table>
  <thead>
    <tr>
      <th>Image </th>
      <th>Device </th>
      <th>Applicant/Manufacturer</th>
      <th>Generic name</th>
      <th>Trade name</th>
      <th>PMA/PMN Number</th>
    </tr>
  </thead>

  <tbody>
    <% @medicaldevices.each do |medicaldevice| %>
      <tr>
        <td><%= image_tag medicaldevice.image_url%></td>
        <td><%= link_to medicaldevice.generic_name, medicaldevice_path(medicaldevice) %></td>
        <td><%= medicaldevice.applicant %></td>
        <td><%= medicaldevice.generic_name %></td>
        <td><%= medicaldevice.trade_name %></td>
        <td><%= medicaldevice.pmak_number %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

      

app/views/pages/index.html.erb
<div class="container">
  <div class="row">
        <div id="container2">
                        <div class="rotator-box">
                          <a class="rotator" ><img class ="rotator" src ="/assets/welcome2.png" alt="device welcome" ></a>
                              <ul class= "info">
                                <li>128,634 Listed Medical devices </li>
                                <li>230 How to Use Instructions </li>
                                <li>136 How to Use Videos </li>
                              </ul>
                        </div>
        </div>

        <div class="rotator-bottom">
        </div>
  </div>

  <div class="row">

      <div class= "search-box">
        <%= render 'layouts/search' %>
      </div>

      <div id="device-box">

            <% if @medicaldevices.present? %>

            <h1>Medical Devices Directory</h1>

            <table>
              <thead>
                <tr>
                  <th>Device Image </th>
                  <th>Generic Name</th>
                  <th>Trade name</th>
                  <th>Manufacturer</th>
                </tr>
              </thead>

              <tbody>
                  <% @medicaldevices.each do |medicaldevice| %>

                        <tr height = "50px" class= "<%= cycle('list_line_odd', 'list_line_even') %>">
                          <td width= "80px">
                            <%= link_to image_tag(medicaldevice.image_url, class: 'deviceimage-thumbnail'), medicaldevice_path(medicaldevice)%>
                          </td>

                          <td>
                            <%= link_to medicaldevice.generic_name, medicaldevice_path(medicaldevice) %>
                          </td>
                          <td>
                            <% if medicaldevice.generic_name.present? %>
                            <%= medicaldevice.trade_name %>
                            <%else %>
                             <%= link_to medicaldevice.trade_name, medicaldevice_path(medicaldevice)%>
                             <%end %>
                          </td>

                          <td>
                            <%= medicaldevice.applicant %>
                          </td>
                        </tr>
                      <% end %>
              </tbody>
            </table>
            <% else %>
            <div>Sorry! No Devices Found. Please Contact Us for More info.</div>
            <% end %>

            <br>

            <%= link_to 'Home', root_path, :class => 'btn btn-primary' %>
      </div>
  </div>
</div>

app/views/pages/mdr.html.erb
<% content_for :title do %>Information on Medical Device Reporting<% end %>
<div class="row">
	<div class="container">
		<h1>Medical Device Reporting! </h1>
	</div>
</div>

app/views/pages/mma.html.erb
<% content_for :title do %>Information on Mobile Medical Applications<% end %>
<div class="row">
	<div class="container">
		<h1>Mobile Medical Applications: </h1>
    <h4>1. What are Mobile Medical Apps? </h4>
    <p>
      Mobile medical apps are medical devices that are mobile apps, meets the definition of a medical device and are an accessory to a regulated medical device or transform a mobile platform into a regulated medical device.
    </p>
    <p>
      According to FDA definition:
    </p>
    <p>
      A “mobile medical app” is a mobile app that meets the definition
of device in section 201(h) of the Federal Food, Drug, and Cosmetic Act (FD&C Act); and
either is intended:
<ul>
  <li>to be used as an accessory to a regulated medical device; or </li>
  <li>to transform a mobile platform into a regulated medical device.</li>
</ul>
    </p>

    <p>

      In general, if a mobile app is intended for use in performing a medical device function (i.e. for
      diagnosis of disease or other conditions, or the cure, mitigation, treatment, or prevention of
      disease) it is a medical device, regardless of the platform on which it is run.
    </p>
    <p>
        For example, mobile apps intended to run on smart phones to analyze and interpret EKG waveforms to detect
      heart function irregularities would be considered similar to software running on a desktop
      computer that serves the same function, which is regulated under 21 CFR 870.2340
      (“Electrocardiograph”).
    </p>

    <p>
        FDA’s oversight approach to mobile apps is focused on their
        functionality, just as it focuses on the functionality of conventional devices. FDA's oversight is not determined by the platform. Under this guidance, FDA would not regulate the sale or
        general/conventional consumer use of smartphones or tablets.
    </p>

    <p>

        FDA’s oversight applies to mobile
        apps performing medical device functions, such as when a mobile medical app transforms a
        mobile platform into a medical device. However, as previously noted, FDA intend to apply this
        oversight authority only to those mobile apps whose functionality could pose a risk to a patient’s
        safety if the mobile app were to not function as intended.
    </p>




        <div class=" ">

            <h4> If you are looking for designing and developing any medical device mobile app, do not hesitate to write:  <%= link_to "Contact Us", new_contact_path, :class =>"btn btn-success btn-sm" %></h4>
        </div>


	</div>
</div>

app/views/pages/privacy.html.erb
<% content_for :title do %>Information on Privacy<% end %>
<div class="row">
	<div class="container">
		<h1> Information on Privacy </h1>
	</div>
</div>

app/views/pages/show.html.erb
<%= render 'layouts/search' %>

<% if @medicaldevices.present? %>
<h1>Listing medicaldevices</h1>

<table>
  <thead>
    <tr>
      <th>Device </th>
      <th>Pmak number</th>
      <th>Applicant</th>
      <th>Generic name</th>
      <th>Trade name</th>
      <th>Product code</th>
    </tr>
  </thead>

  <tbody>
    <% @medicaldevices.each do |medicaldevice| %>
      <tr>
        <td><%= link_to medicaldevice.generic_name, medicaldevice_path(medicaldevice) %></td>
        <td><%= medicaldevice.pmak_number %></td>
        <td><%= medicaldevice.applicant %></td>
        <td><%= medicaldevice.generic_name %></td>
        <td><%= medicaldevice.trade_name %></td>
        <td><%= medicaldevice.product_code %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% else %>
<div>No devices</div>
<% end %>

<br>

<%= link_to 'Back', pages_path, :class => 'btn btn-primary' %>

app/views/pages/tos.html.erb
<% content_for :title do %>Terms of Service<% end %>
<div class="row">
	<div class="container">
		<h1> Terms of Service </h1>
	</div>
</div>

app/views/pages/udi.html.erb
<% content_for :title do %>Information on UDI<% end %>
<div class="row">
	<div class="container">
		<h1> Unique Device Identification: </h1>
	</div>
</div>