config/routes.rb
Medicaldevicehub::Application.routes.draw do

  resources :videourls

  ActiveAdmin.routes(self)

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  devise_for :admin_users, ActiveAdmin::Devise.config
  devise_for :manufacturers

  root :to => 'pages#index'

  get 'about' => 'pages#about'
  get 'mdr' => 'pages#mdr'
  get 'mma' => 'pages#mma'
  get 'privacy' => 'pages#privacy'
  get 'tos' => 'pages#tos'
  get 'udi' => 'pages#udi'
  get 'contacts' => 'contacts#new'

  resources :medicaldevices, except: [:destroy, :edit, :update]

  resources :device_reviews

  resources :manufacturers

  resources :contacts, only: [:new, :create]

  resources :medicaldevices do
    resources :videourls
  end
  resources :manufacturers do
    resources :videourls
  end

end

app/views/layouts/_footer.html.erb
<!-- begin footer -->
  <footer id="footer">
      <div class="container">
        <div class="row">
            <!-- begin footer top -->
            <div id="footer-top">
                <div class="one-fourth">
                  <div class="widget">
                        <h3>Site Menu</h3>
                        <ul>
                              <li><%= link_to "Home", root_path %></li>
                              <li><%= link_to "UDI", page_path('udi') %></li>
                              <li><%= link_to "MDR", page_path('mdr') %></li>
                              <li><%= link_to "MMA", page_path('mma') %></li>
                              <li><%= link_to "About Us" , page_path('about') %></li>
                              <li><%= link_to "Contact Us", new_contact_path %></li>
                        </ul>
                    </div>
                </div>
                <div class="one-fourth">
                  <div class="widget latest-posts">
                        <h3>Useful Links:</h3>
                        <ul>
                            <li><a href="#">Recent Medical Device Recall</a></li>
                            <li><a href="#">Unique Device Identification</a></li>
                            <li><a href="#">FDA</a></li>
                            <li><a href="#">Portfolio</a></li>
                            <li><a href="#">Blog</a></li>
                            <li><a href="#">Contact</a></li>
                        </ul>
                    </div>
                </div>
                <div class="one-fourth">
                  <div class="widget twitter-widget">
                      <h3>Site Info.</h3>
                        <div class="tweet">
                          <ul>
                              <li><%= link_to "Terms of Service", page_path('tos') %></li>
                              <li><%= link_to "Privacy", page_path('privacy') %></li>
                              <li><%= link_to "MDR", page_path('mdr') %></li>
                              <li><%= link_to "MMA", page_path('mma') %></li>
                              <li><%= link_to "About Us" , page_path('about') %></li>
                              <li><%= link_to "Contact Us", new_contact_path %></li>
                            </ul>
                        </div>
                    </div>
                </div>
                <div class="one-fourth column-last">
                  <div class="widget contact-info">
                      <h3>Contact Info</h3>
                        <p class="address"><strong>Address:</strong> 123 Street, City, Country</p>
                        <p class="phone"><strong>Phone:</strong> (123) 456-7890</p>
                        <p class="email"><strong>Email:</strong> <a href="mailto:admin@medicaldevicehub.com">admin@medicaldevicehub.com</a></p>
                        <div class="social-links">
                          <h4>Follow Us</h4>
                            <ul>
                              <li class="twitter"><a href="https://twitter.com/mdevicehub" title="Twitter" target="_blank">Twitter</a></li>
                                <li class="facebook"><a href="https://www.facebook.com/medicaldevicehub" title="Facebook" target="_blank">Facebook</a></li>
                                <li class="google"><a href="https://plus.google.com/109411993303954220077/about" title="Google+" target="_blank">Google+</a></li>
                                <li class="youtube"><a href="https://www.youtube.com/channel/UCBSBbve6XBCIAdU5g4x30Tw/" title="YouTube" target="_blank">YouTube</a></li>
                                <li class="rss"><a href="#" title="RSS" target="_blank">RSS</a></li>
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
            <!-- end footer top -->

            <!-- begin footer bottom -->
            <div id="footer-bottom">
              <div class="one-half">
                  <p>Copyright &copy; 2014 All rights reserved.  <%= link_to 'MedicalDeviceHub','http://medicaldevicehub.com' %></a>.
                  </p>

                </div>

                <div class="one-half column-last">

                </div>
            </div>
            <!-- end footer bottom -->
          </div>
        </div>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-45241437-1', 'medicaldevicehub.com');
  ga('send', 'pageview');
</script>
</footer>
  <!-- end footer -->

app/views/layouts/_header.html.erb
<!-- Brand and toggle get grouped for better mobile display -->
<div class="container">
        <div class="row">

            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>

              <a href="/" class="brand" ><img class ="logo" src ="/assets/MDH_logo1.png" alt="Medical Device Hub logo" ></a>


            <!-- Collect the nav links, forms, and other content for toggling -->



                    <ul class="nav nav-pills pull-right top-nav">
                      <% if user_signed_in? %>
                	                      		Logged in as <strong><%= current_user.name %></strong>
                	                        		<li><%= link_to "Edit Account", edit_user_registration_path %></li>
                	                       			<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
                	                      		<% else %>
                	                      			<li><%= link_to "User Log in", new_user_session_path %></li>
                	                      			<li><%= link_to "User Sign up", new_user_registration_path %></li>
                	                      		<% end %>

                                            <% if manufacturer_signed_in? %>
                                            Logged in as Manufacturer <strong><%= current_manufacturer.username %></strong>
                                              <li><%= link_to "Edit Account", edit_manufacturer_registration_path %></li>
                                              <li><%= link_to "Logout", destroy_manufacturer_session_path, method: :delete %></li>
                                            <% else %>
                                              <li><%= link_to "Manufacturer Log in", new_manufacturer_session_path %></li>
                                              <li><%= link_to "Manufacturer? Contact Us", new_contact_path %></li>
                                            <% end %>
                    </ul>
                  <!-- /.navbar-collapse -->



        <nav class="navbar navbar-default fhmm" role="navigation">

          <div class="menudrop container">
                        <div class="navbar-header">
                            <button type="button" data-toggle="collapse" data-target="#defaultmenu" class="navbar-toggle"><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span></button>
                        </div><!-- end navbar-header -->

                        <div id="defaultmenu" class="navbar-collapse collapse">
                            <ul class="nav navbar-nav">
                                <!-- Mega Menu -->
                                <li class="dropdown fhmm-fw active"><a href="/"><i class="fa fa-home"></i> HOME</a></li><!-- mega menu -->

                                <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">SERVICES <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li><%= link_to "Unique Device Identification", page_path('udi') %></li>
                                        <li><%= link_to "Medical Device Reporting", page_path('mdr') %></li>
                                    </ul><!-- end dropdown-menu -->
                                </li><!-- end standard drop down -->

                                <li class="dropdown"><a href="#" data-toggle="dropdown" class="dropdown-toggle">TOOLS <b class="caret"></b></a>
                                    <ul class="dropdown-menu" role="menu">
                                          <li><%= link_to "Mobile Medical Application", page_path('mma') %></li>
                                          <li><%= link_to "Medical Device Application", page_path('mdr') %></li>
                                    </ul><!-- end dropdown-menu -->
                                </li><!-- end standard drop down -->


                                <li><%= link_to "ABOUT US" , page_path('about') %></li>

                                <li><%= link_to "CONTACT US", new_contact_path %></li>
                            </ul><!-- end nav navbar-nav -->
                        </div><!-- end #navbar-collapse-1 -->
                     </div><!-- end dm_container -->
            </nav><!-- end navbar navbar-default fhmm -->
          </div><!-- end row -->
        </div><!-- end container -->

app/views/layouts/_navigation_links.html.erb
<li><%= link_to 'About', page_path('about') %></li>
<li><%= link_to 'Contact', new_contact_path %></li>

app/views/layouts/_search.html.erb
<section class="search">
	<form action="/medicaldevices" method="get" class= "search-wrapper cf">
		<div class ="wrapper">
			<input name="utf8" type="hidden" value="&#x2713;" />
			<input id="query" name="query" type="text" placeholder="Search Medical Device" />
	    	<button type="submit" value="Search" class="search-button">Search</button>
		</div>
	</form>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>
     <%= content_for?(:title) ? yield(:title) : "Medical Device Hub| Worldwide Hub For Medical Devices" %>
  </title>
  <meta name='description' content="<%= content_for?(:description) ? yield(:description) : 'Find medical devices available worldwide. Get information on any medical device photos, reviews, how to videos and more!' %>" >
  <meta content='Information on Medical Device identification, review, how to use, reporting and tracking' name='description'>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>
<body>

	<div class=" ">
		<%= render 'layouts/header' %>
          <% flash.each do |name, msg| %>
           <%= content_tag(:div, msg, class: "alert alert-info") %>
          <% end %>


		<%= yield %>

	</div>
  <%= render 'layouts/footer' %>

</body>
</html>